### ISSUE TITLE
Snap Roadmap

### ISSUE THREAD

**Issue by daPhipz** [muesli/duf#29]
Because making a snap seems not as easy (#25), I wanted to use this issue as a bit of a roadmap to track problems, To Dos and other useful information. Feel free to either edit this directly or suggest things via commenting.

---

### To Do

- [ ] Fix the cluttered output described in #25 when using the snap
- [ ] Maybe create an extra `snap` branch for easier collaboration and to keep snap development away from the rest of the project
- [ ] Write tests to check whether the snap builds correctly (I've started this [here](https://github.com/daPhipz/duf/tree/action)). Unfortunately (afaik), you can only have one `snapcraft.yaml` per project. Therefore, we can't have one `yaml` producing the "production" releases on every pushed tag and another one checking every commit/PR for errors.
- [ ] Create a snapcraft developer account and upload the snap. They have some sort of GitHub integration built into their infrastructure as well, might be worth a look.

### Done

- [x] Produce a snap with a valid `snapcraft.yaml`
- [x] Make the snap's version number change automatically with every new release

**Comment by julian-klode** [comment]
In the meantime, I think if you make it a classic snap, that should yield a usable result? But not 100% sure, but if it works, better than no snap :)

**Comment by muesli** [comment]
Update:

- I've created a developer account and @popey has transferred the package to me: https://snapcraft.io/duf-utility
- The snaps are automatically built along with all the other releases by goreleaser: #109 
- @julian-klode has decluttered the output a bit with #100.

**Comment by muesli** [comment]
As the current snap sandbox is too constrained for a tool like `duf`, the snap package is currently unmaintained. For recent Debian & Ubuntu installs you can simply run `apt install duf` now. Also see #148 and #21.
